keys:
  - &users:
    - &snregales age1974szkpxle4kpc3jjcdwna4f338mz342vw4ywnata8wzpaw7eflqramwlq
  - &hosts:
    - &dell-xps-9640 age1pxr7m4rklq2a5ydx53l22vq86mpp2cwt0w5ey8yv86gueu9lcdnsyzu26f
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *snregales
      - *dell-xps-9640
